### ISSUE TITLE
I try to compile LearningRPMWPM but error

### ISSUE THREAD

**Issue by 1145738769** [UrAvgCoder/ring0-csg0#1]
Invalid argument <CN="WDKTestCert Another User,132514926414867388" | 27F22EFD094EFB435217B73E2413FF10B4231564> for property . LearningRPMWPM D:\Windows Kits\10\build\WindowsDriver.common.targets 1435

**Comment by UrAvgCoder** [comment]
Hey, you need to generate a new Test Certificate inside Visual Studio 2019 for it to sign the driver. 
![testsigning](https://user-images.githubusercontent.com/35104670/101277971-05880600-37de-11eb-8e43-b06580a051c0.png)
Choose the "Create Test Certificate" from the drop-down box.
